#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/snort

start_service() {	

	procd_open_instance
	procd_set_param command /usr/bin/snort-start
	procd_set_param env SNORT_LUA_PATH="$config_dir"
	procd_set_param file $CONFIGFILE
	procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
	procd_close_instance
}

stop_service()
{
	service_stop ${PROG}
}

service_triggers()
{
	procd_add_reload_trigger "snort"
}
